### ISSUE TITLE
mat-dialog-content

### ISSUE THREAD

**Issue by bensaadmohamed** [elementarlabs/elementar-admin#3]
hello
mat-dialog-content typography hierarchy wont render correctly in Dialog With Scrollable Content example

**Comment by spvcoder** [comment]
Hello, do you have an example to reproduce the error or a screenshot?

**Comment by bensaadmohamed** [comment]
hello yes here is a screenshot from the scrollable dialog component example where the p tag and h3 heading tag have the  some font size and the  typography hierarchy from angular material didnt applied correctley
![Untitled](https://github.com/user-attachments/assets/73946c80-7651-4db1-b0f6-0256b802dc5c)

**Comment by spvcoder** [comment]
Thanks, for a quick fix, I added `prose` CSS class instead of `mat-typography`. And for mat-typography I will add CSS styles soon. I already updated the demo, check it out https://demo.elementarui.com/pages/components/dialog.

**Comment by bensaadmohamed** [comment]
ok thanks man keep good work,i ll check it
